### ISSUE TITLE
Service Bus Scaler fails with = in connection String

### ISSUE THREAD

**Issue by rangp** [kedacore/keda#1181]
I'm not sure about the root cause, but when setting up my scaler, I find the following error message in the log

`azure_servicebus_scaler	error	{"error": "failed parsing connection string due to unmatched key value separated by '='"}`

Upon investigating I found that my SharedAccessKey contains a "=" since it is base64 encoded by default. I suspect that this could be the problem, as I copied the connection string right from the azure portal and it works fine when connecting via ServiceBusExplorer

## Steps to Reproduce the Problem

My template for the ScaledObject

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.app.name }}-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: StatefulSet
    name: {{ .Values.app.name }}
  maxReplicaCount: 10
  minReplicaCount: 1
  triggers:
  - type: azure-servicebus
    metadata:
      topicName: my-topic
      subscriptionName: general-subscription
      connectionFromEnv: SERVICEBUS_CONNECT
      queueLength: "4000"
```

where SERVICEBUS_CONNECT looks like

`Endpoint=sb://my-bus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=somethingBase64WhichHasAPaddingOf=;EntityPath=my-topic`

## ExpectedBehaviour

I would expect the connection string to be valid, since it can be parsed by the service bus explorer and the c# SDK likewise. 

## Specifications

  - **KEDA Version:** *2.0.0 beta*
  - **Platform & Version:** *Azure Kubernetes Service*
  - **Kubernetes Version:** *1.17.9*
  - **Scaler(s):** *Azure Service Bus*

**Comment by tomkerkhove** [comment]
We'll look into it, thanks! Do keep in mind that `queueLength` was changed to `messageCount` since this is confusing for topics. See: https://keda.sh/docs/2.0/migration/

**Comment by rangp** [comment]
@tomkerkhove Thank you for the information. I saw both values in the documentation but did not see the migration guide

**Comment by tomkerkhove** [comment]
Was it in 2.0 docs or 1.x?

**Comment by rangp** [comment]
In 1.x.

I started with the documentation for 2.0, then read this [sample](https://github.com/felipecruz91/sample-dotnet-consumer-servicebus-topic) which I believe is for 1.x only. This led me back to the 1.x documentation without realizing it. 

I mean, if I can make a suggestion: For a beginner to keda it would proably be helpful if the samples specified which version is used at the beginning and perhaps point to the migration guide, for older versions.

**Comment by tomkerkhove** [comment]
Thanks for the feedback, unfortunately we don't maintain that one but I'll try to update all of our samples to at least specify the version.

**Comment by tomkerkhove** [comment]
Ok to close this issue then?

**Comment by rangp** [comment]
No. I think the discussion has drifted a bit off-topic. The original issue is that our connection string cannot be parsed and is not related to the queueLength / messageCount confusion. At least I think it isn't

**Comment by rangp** [comment]
In fact I corrected the property name now and it doesn't have an influence on the error message

**Comment by rangp** [comment]
@tomkerkhove I suspect I know what you mean now by "we don't maintain that one". I did some digging on my own and found a different reason for the error message I am getting. I'm closing this issue since it was misleading and opened #1197.

Thanks for the support so far!

**Comment by tomkerkhove** [comment]
Oh thanks for that! Sorry, didn't have time yet to check.

**Comment by Andycharalambous** [comment]
I realize this is now closed, but I don't think #1197 resolves anything  - this problem is still there. I have a scaled-object that uses connectionFromEnv and the env var in the Deployment does not contain any other environment variable references - it's a pure connection string that just happens to have a "=" padding in the SharedAccessKey value. The only thing of note is that I use the following in the deployment:

```
envFrom:
  - secretRef:
      name:  my-secret
```

"my-secret" contains a field that has the topic connection string.
