### ISSUE TITLE
MySQL scaler: Whitespace at the start/end of a `host` configuration value breaks scaling

### ISSUE THREAD

**Issue by TimShilov** [kedacore/keda#2812]
### Report

I've just noticed one of my workloads not scaling properly.
I've spent a lot of time digging it and found that value for `host` taken from Kubernetes secret resource had a line break at the end of it.
This new line is very hard to spot and it's simply invisible when encoded in base64.

The worst part of it is that workloads (Node.js application) was working fine as it seem to trim host automatically.
Since whitespaces are not allowed in host (I think) would be great if KEDA would trim the value from extra whitespace on the start and end.

### Expected Behavior

- Workload should be scaled successfully
OR
- Workload should be scaled to fallback.replicas value

### Actual Behavior

Workload is scaled to `minReplicaCount`

### Steps to Reproduce the Problem

1. Create a Deployment
2. Create a Secret with connection details.
3. Add a whitespace at the end of the secret value that will be used as `host` (add `Cg==` at the end of the encoded value)
4. Create a ScaledObject with any valid MySQL scaler configuration 

### KEDA Version

2.5.0

### Kubernetes Version

1.21

### Platform

Google Cloud

### Scaler Details

MySQL

**Comment by JorTurFer** [comment]
Hi @TimShilov 
Could you try your case with the latest version? In v2.6.x we introduced a lot of improvements. 
If I'm not wrong, this PR changed that behaviour to solve that problem. Is any error shown on KEDA logs (operator or metrics-server)?

**Comment by TimShilov** [comment]
Hi @JorTurFer .
Yesterday I've updated KEDA to 2.6.1 and the problem is still not resolved.
Here's an example of what's shown in Events when whitespace is at the beginning of the value:
```
Warning  KEDAScalerFailed            2m11s                keda-operator  error parsing MySQL metadata: no host given
```
And here's an example of what's shown when whitespace is at the end of the value (notice the line break between the IP and `no such host`:
```
Warning  KEDAScalerFailed         4m2s (x20 over 42m)  keda-operator  error establishing MySQL connection: dial tcp: lookup 10.1.18.3                                                                                            
: no such host                                                                                                                                                                                                                     
```

I couldn't find anything worthy in the operator logs because I have a huge amount of scaled objects and there's just too much output. I will try to catch an error later and will add it if I'll find anything.

**Comment by JorTurFer** [comment]
The point is that in this case, the problem is related with the configuration. IMO doesn't make sense to use fallback config because this scaler is basically broken till the config is fixed. 
From the logs you have sent, I can see that error is correctly notified, so I guess that the error metric is taking into account also from  Prometheus pov (so an alert can be raised).
Do you think that using fallback configuration is worth in this case @TimShilov ? I mean, you will hide the error.
@kedacore/keda-core-contributors ?

**Comment by TimShilov** [comment]
> From the logs you have sent, I can see that error is correctly notified

I don't think that "no host given" for example is a correct message in case when a **given** value starts with a line break.

> Do you think that using fallback configuration is worth in this case @TimShilov ? I mean, you will hide the error.

I don't consider this exact case with extra whitespace an error and ideally I would've prefer the value to just be trimmed and work just fine. For example, [node-mysql2](https://github.com/sidorares/node-mysql2) does that and just works with the same exact configuration and I'm pretty sure other MySQL clients also do that. Just tried to enter a host with a whitespace to [Sequel Ace](https://github.com/Sequel-Ace/Sequel-Ace) and it is also gets trimmed and works fine.

Also, if thee value cannot just be trimmed I do think that using fallback makes perfect sense to me. I see "fallback" as a "if anything fails, use this value". In this case scaler cannot connect and thus - not working, I would expect it to use a fallback.

The main point I'm trying to communicate is I had this case and had a hard time figuring it out. I had a scaler that didn't worked and a workload that worked just fine using the same exact configuration. I checked the scaler and it showed me "no host given" even though the host was clearly there. I've copy-pasted the value but obviously line break is not the most visible character so it took some time to figure out.

**Comment by JorTurFer** [comment]
any thoughts @kedacore/keda-core-contributors ?

**Comment by zroubalik** [comment]
I think that it makes sense to trim all values in trigger metadata, this could be done in the effort in refactoring the metadata parsing for all scaler?

**Comment by TimShilov** [comment]
That's still an issue.

If that's okay I may try to make a PR myself. Since I've never contributed to this project yet any guidance will be appreciated (should I update on scaler or as @zroubalik mentioned it's best to do this for all scalers?).
